export { welcomeTemplate } from './welcome'
export { purchaseConfirmationTemplate } from './purchase-confirmation'
export { subscriptionRenewalTemplate } from './subscription-renewal'
export { videoCompletedTemplate } from './video-completed'
export { passwordResetTemplate } from './password-reset'

export type { WelcomeEmailData } from './welcome'
export type { PurchaseConfirmationData } from './purchase-confirmation'
export type { SubscriptionRenewalData } from './subscription-renewal'
export type { VideoCompletedData } from './video-completed'
export type { PasswordResetData } from './password-reset'