import { baseTemplate } from './base-template'
import { escapeHtml } from '@/lib/utils/sanitize'
import { EMAIL_URLS } from '@/config/urls'

export interface VideoCompletedData {
  customerName: string
  videoTitle: string
  videoId: string
  provider: string
  duration: number
  downloadUrl?: string
}

export const videoCompletedTemplate = (data: VideoCompletedData) => {
  const body = `
    <p>Hi ${escapeHtml(data.customerName)},</p>
    <p>Great news! Your video is ready!</p>
    
    <div class="order-details">
      <h2>Video Details</h2>
      <div class="item">
        <span>Title</span>
        <span>${escapeHtml(data.videoTitle)}</span>
      </div>
      <div class="item">
        <span>Duration</span>
        <span>${data.duration} seconds</span>
      </div>
      <div class="item">
        <span>Generated by</span>
        <span>${escapeHtml(data.provider)}</span>
      </div>
    </div>
    
    <div style="text-align: center;">
      ${data.downloadUrl ? `
        <a href="${data.downloadUrl}" class="button">Download Video</a>
        <br>
        <small style="color: #666;">This link will expire in 24 hours</small>
      ` : `
        <a href="${EMAIL_URLS.getVideoUrl(data.videoId)}" class="button">View Video</a>
      `}
    </div>
    
    <p>Thank you for using Kylo to bring your ideas to life!</p>
  `

  return {
    subject: '🎬 Your video is ready!',
    html: baseTemplate({
      title: 'Video Generation Complete!',
      body
    })
  }
}